---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateways-options
  namespace: default
  labels:
    app: is-spinnaker-gateway
data:
  options_0: |-
    {
      "rabbitmq_uri": "amqp://rabbitmq.default",
      "zipkin_uri" : "http://zipkin.default:9411",
      "camera": {
        "id": 0,
        "ip": "10.20.6.0",
        "algorithm": "BILINEAR",
        "onboard_color_processing": false,
        "packet_size": 1400,
        "packet_delay": 6000,
        "packet_resend": true,
        "packet_resend_timeout": 100,
        "packet_resend_max_requests": 10000,
        "reverse_x": false,
        "use_turbojpeg": true,
        "restart_period": 3600,
        "initial_config": {
          "sampling": {
            "frequency": 10.0
          },
          "image": {
            "color_space": {
              "value": "RGB"
            },
            "format": {
              "format": "JPEG",
              "compression": 0.8
            }
          },
          "camera": {
            "gain": {
              "automatic": true
            }
          }
        }
      }
    }
  options_1: |-
    {
      "rabbitmq_uri": "amqp://rabbitmq.default",
      "zipkin_uri" : "http://zipkin.default:9411",
      "camera": {
        "id": 1,
        "ip": "10.20.6.1",
        "algorithm": "BILINEAR",
        "onboard_color_processing": false,
        "packet_size": 1400,
        "packet_delay": 6000,
        "packet_resend": true,
        "packet_resend_timeout": 100,
        "packet_resend_max_requests": 10000,
        "reverse_x": false,
        "use_turbojpeg": true,
        "restart_period": 3600,
        "initial_config": {
          "sampling": {
            "frequency": 10.0
          },
          "image": {
            "color_space": {
              "value": "RGB"
            },
            "format": {
              "format": "JPEG",
              "compression": 0.8
            }
          },
          "camera": {
            "gain": {
              "automatic": true
            }
          }
        }
      }
    }
  options_2: |-
    {
      "rabbitmq_uri": "amqp://rabbitmq.default",
      "zipkin_uri" : "http://zipkin.default:9411",
      "camera": {
        "id": 2,
        "ip": "10.20.6.2",
        "algorithm": "BILINEAR",
        "onboard_color_processing": false,
        "packet_size": 1400,
        "packet_delay": 6000,
        "packet_resend": true,
        "packet_resend_timeout": 100,
        "packet_resend_max_requests": 10000,
        "reverse_x": false,
        "use_turbojpeg": true,
        "restart_period": 3600,
        "initial_config": {
          "sampling": {
            "frequency": 10.0
          },
          "image": {
            "color_space": {
              "value": "RGB"
            },
            "format": {
              "format": "JPEG",
              "compression": 0.8
            }
          },
          "camera": {
            "gain": {
              "automatic": true
            }
          }
        }
      }
    }
  options_3: |-
    {
      "rabbitmq_uri": "amqp://rabbitmq.default",
      "zipkin_uri" : "http://zipkin.default:9411",
      "camera": {
        "id": 3,
        "ip": "10.20.6.3",
        "algorithm": "BILINEAR",
        "onboard_color_processing": false,
        "packet_size": 1400,
        "packet_delay": 6000,
        "packet_resend": true,
        "packet_resend_timeout": 100,
        "packet_resend_max_requests": 10000,
        "reverse_x": false,
        "use_turbojpeg": true,
        "restart_period": 3600,
        "initial_config": {
          "sampling": {
            "frequency": 10.0
          },
          "image": {
            "color_space": {
              "value": "RGB"
            },
            "format": {
              "format": "JPEG",
              "compression": 0.8
            }
          },
          "camera": {
            "gain": {
              "automatic": true
            }
          }
        }
      }
    }
